name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.3.3
    - name: Set up JDK    
      uses: actions/setup-java@v3.4.0    
      with:        
        java-version: 18
        distribution: zulu
    - name: Build with Maven      
      run: mvn package spring-boot:repackage
    - name: Publish to Docker Hub
      uses: docker/build-push-action@v1
      with:
       username: ${{ secrets.DOCKER_HUB_USERNAME }}
       password: ${{ secrets.DOCKER_HUB_PASSWORD }}
       repository: sunilsharmadocker/github-actions-demo
       tags: ${{github.run_number}}
